### ISSUE TITLE
Plugin breaks other plugins' CSS injections

### ISSUE THREAD

**Issue by Leo40Git** [Tharki-God/DevtoolsBandage#1]
See https://github.com/Penguin-Spy/replugged-pronoundb/issues/9.

**Comment by yofukashino** [comment]
ig i can make it replace every CSS to avoid that

**Comment by Leo40Git** [comment]
Hold off on that for now, this might actually be Replugged's general instability right now.

**Comment by yofukashino** [comment]
whatever I will make it fix for myself
